src/askLNU/askLNU/ViewModels/CreatedQuestionsViewModel.cs
namespace askLNU.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class CreatedQuestionsViewModel
    {
        public int Id { get; set; }

        public string ApplicationUserID { get; set; }

        public string Title { get; set; }

        public string Text { get; set; }

        public int Rating { get; set; }

        public bool IsFavorite { get; set; }

        public bool IsSolved { get; set; }

        public DateTime Date { get; set; }
    }
}

src/askLNU/askLNU/ViewModels/QuestionViewModel.cs
namespace askLNU.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class QuestionViewModel
    {
        public int Id { get; set; }

        public UserShortViewModel Author { get; set; }

        public string Title { get; set; }

        public string Text { get; set; }

        public int Rating { get; set; }

        public bool IsSolved { get; set; }

        public DateTime Date { get; set; }

        public bool IsFavorite { get; set; }

        public string Faculty { get; set; }

        public List<string> Tags { get; set; }
    }
}

src/askLNU/askLNU/Controllers/AnswerController.cs
namespace askLNU.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using askLNU.BLL.Interfaces;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    public class AnswerController : Controller
    {
        private readonly IUserService userService;
        private readonly IAnswerService answerService;
        private readonly ILogger<AnswerController> logger;

        public AnswerController(
            IUserService userService,
            IAnswerService answerService,
            ILogger<AnswerController> logger
            )
        {
            this.userService = userService;
            this.answerService = answerService;
            this.logger = logger;
        }

        [HttpPost]
        public int VoteUp([FromForm] int answerId)
        {
            var userId = this.userService.GetUserId(this.User);
            var rating = this.answerService.VoteUp(userId, answerId);
            return rating;
        }

        [HttpPost]
        public int VoteDown([FromForm] int answerId)
        {
            var userId = this.userService.GetUserId(this.User);
            var rating = this.answerService.VoteDown(userId, answerId);
            return rating;
        }

        [Authorize(Roles = "Moderator,Admin")]
        public ActionResult Delete([FromForm] int answerId, [FromForm] int questionId)
        {
            this.logger.LogInformation($"Moderator deleted answer with id {answerId}.");
            this.answerService.Dispose(answerId);
            return this.RedirectToAction("Details", "Question", new { id = questionId });
        }
    }
}

src/askLNU/askLNU/Controllers/LoginController.cs
namespace askLNU.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using askLNU.BLL.Interfaces;
    using askLNU.DAL.Entities;
    using askLNU.InputModels;
    using askLNU.ViewModels;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    public class LoginController : Controller
    {
        private readonly ISignInService _signInService;
        private readonly ILogger<LoginController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;


        public LoginController(ISignInService signInService, ILogger<LoginController> logger, UserManager<ApplicationUser> userManager)
        {
            this._signInService = signInService;
            this._logger = logger;
            this._userManager = userManager;

        }

        public async Task<IActionResult> Index()
        {
            await this.HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            var viewModel = new LoginViewModel
            {
                ExternalLogins = new List<AuthenticationScheme>(),
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Login(LoginInputModel loginInputModel)
        {
            if (this.ModelState.IsValid)
            {
                var user = this._userManager.FindByNameAsync(loginInputModel.UserName);
                if (user.Result != null && user.Result.IsBlocked)
                {
                    this.ModelState.AddModelError("RememberMe", "You are blocked.");
                    return this.View("Index");
                }

                var result = await this._signInService.PasswordSignInAsync(loginInputModel.UserName, loginInputModel.Password, loginInputModel.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    this._logger.LogInformation("User logged in.");
                    return this.RedirectToAction("Index", "Home");
                }

                if (result.RequiresTwoFactor)
                {
                    // return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }

                if (result.IsLockedOut)
                {
                    this._logger.LogWarning("User account locked out.");
                    return this.RedirectToPage("./Lockout");
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return this.View("Index");
                }
            }

            return this.View("Index");
        }
    }
}

src/askLNU/askLNU/Controllers/QuestionController.cs
namespace askLNU.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using askLNU.BLL.DTO;
    using askLNU.BLL.Infrastructure.Exceptions;
    using askLNU.BLL.Interfaces;
    using askLNU.DAL.Entities;
    using askLNU.InputModels;
    using askLNU.ViewModels;
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    [Authorize(Roles = "User")]
    public class QuestionController : Controller
    {
        private readonly IFacultyService _facultyService;
        private readonly ITagService _tagService;
        private readonly IQuestionService _questionService;
        private readonly IUserService _userService;
        private readonly IAnswerService _answerService;
        private readonly ILogger<QuestionController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private Mapper _mapper;

        public QuestionController(
             UserManager<ApplicationUser> userManager,
            IFacultyService facultyService,
            ITagService tagService,
            IQuestionService questionService,
            IUserService userService,
            ILogger<QuestionController> logger,
            IAnswerService answerService)
        {
            this._userManager = userManager;
            this._facultyService = facultyService;
            this._tagService = tagService;
            this._questionService = questionService;
            this._userService = userService;
            this._answerService = answerService;
            this._logger = logger;
            var config = new MapperConfiguration(cfg => cfg.CreateMap<QuestionDTO, CreatedQuestionsViewModel>());
            this._mapper = new Mapper(config);
        }

        [AllowAnonymous]
        [HttpGet("{controller}/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var question = this._questionService.GetQuestion(id);
                var author = await this._userService.GetByIdAsync(question.ApplicationUserId);
                var authorViewModel = new UserShortViewModel
                {
                    UserName = author.UserName,
                    ImageSrc = author.ImageSrc,
                };

                var viewModel = new QuestionViewModel
                {
                    Id = question.Id,
                    Title = question.Title,
                    Text = question.Text,
                    Date = question.Date,
                    Author = authorViewModel,
                    Tags = question.TagsId.Select(id => this._tagService.GetTag(id).Text).ToList(),
                    Rating = question.Rating,
                };

                return this.View(viewModel);
            }
            catch (ItemNotFoundException exception)
            {
                return this.RedirectToAction("ShowError", "CustomError", new { errorMessage = exception.Message });
            }
        }


        public ActionResult TopTen()
        {
             var questions=_questionService.GetAll().OrderByDescending(i => i.Rating).Take(1); 
            return View(questions);
        }

        public IActionResult Create()
        {
            var viewModel = new CreateQuestionViewModel
            {
                Faculties = this._facultyService.GetAll().ToList(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(QuestionInputModel questionInput)
        {
            var questionDTO = new QuestionDTO
            {
                Title = questionInput.Title,
                Text = questionInput.Text,
                FacultyId = questionInput.FacultyId,
                Date = DateTime.Now,
                ApplicationUserId = this._userService.GetUserId(this.User),
            };

            this._questionService.CreateQuestion(questionDTO);

            if (questionInput.Tags != null)
            {
                foreach (var tag in questionInput.Tags)
                {
                    var tagId = this._tagService.FindOrCreate(tag);
                    this._questionService.AddTag(questionDTO.Id, tagId);
                }
            }

            this._logger.LogInformation($"Question #{questionDTO.Id} created.");

            return this.RedirectToAction("Details", "Question", new { id = questionDTO.Id });
        }

        [HttpPost]
        public int VoteUp([FromForm] int questionId)
        {
            var userId = this._userService.GetUserId(this.User);
            var rating = this._questionService.VoteUp(userId, questionId);
            return rating;
        }

        [HttpPost]
        public int VoteDown([FromForm] int questionId)
        {
            var userId = this._userService.GetUserId(this.User);
            var rating = this._questionService.VoteDown(userId, questionId);
            return rating;
        }

        [HttpPost]
        public List<AnswerViewModel> AddAnswer(int? questionId, string answerText)
        {
            if (questionId != null && !string.IsNullOrEmpty(answerText) && !string.IsNullOrWhiteSpace(answerText))
            {
                var answer = new AnswerDTO
                {
                    Text = answerText,
                    ApplicationUserId = this._userService.GetUserId(this.User),
                    Date = DateTime.UtcNow,
                };

                this._questionService.AddAnswer(questionId.Value, answer);

                return this.GetLastAnswers(questionId.Value, 10);
            }
            else
            {
                return null;
            }
        }

        [AllowAnonymous]
        public List<AnswerViewModel> GetLastAnswers(int questionId, int amount)
        {
            var answers = this._answerService.GetAnswersByQuestionId(questionId);
            var sortedAnswers = from answer in answers
                                orderby answer.Date descending
                                orderby answer.IsSolution descending
                                select new AnswerViewModel
                                {
                                    Id = answer.Id,
                                    Text = answer.Text,
                                    Rating = answer.Rating,
                                    IsSolution = answer.IsSolution,
                                    Date = answer.Date.ToLocalTime().ToShortDateString(),
                                    AuthorName = this._userService.GetByIdAsync(answer.ApplicationUserId).Result.UserName,
                                };

            return sortedAnswers.Take(amount).ToList();
        }

        [Authorize(Roles = "Moderator,Admin")]
        public ActionResult DeleteQuestion(int questionId)
        {
            this._logger.LogInformation($"Moderator deleted question with id {questionId}.");
            this._questionService.Dispose(questionId);
            return this.RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Moderator,Admin")]
        public ActionResult DeleteAnswer(int answerId)
        {
            this._logger.LogInformation($"Moderator deleted answer with id {answerId}.");
            this._answerService.Dispose(answerId);
            return this.RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> CreatedQuestions()
        {
            var user = await this._userManager.GetUserAsync(this.User);
            var allQuestions = this._questionService.GetAll().Where(u => u.ApplicationUserId == user.Id);
            var allQuestionsForView = this._mapper.Map<IEnumerable<CreatedQuestionsViewModel>>(allQuestions);
            return this.View(allQuestionsForView);
        }

        public async Task<ActionResult> FavoriteUserQuestions()
        {
            var user = await this._userManager.GetUserAsync(this.User);
            var questions = this._questionService.GetFavQuestByUserId(user.Id);
            var allQuestionsForView = this._mapper.Map<IEnumerable<CreatedQuestionsViewModel>>(questions);
            return this.View(allQuestionsForView);
        }
    }
}

src/askLNU/askLNU/Views/Question/Create.cshtml
@model askLNU.ViewModels.CreateQuestionViewModel

@{
    ViewData["Title"] = "Ask a question";
}
    <style>
        body {
            background-color: lightslategray;
        }

        form {
            margin-bottom: 16px;
        }

        section {
            display: block;
            overflow: auto;
            height: 100%;
            border-radius: 4px;
            background-color: #f8f9fa;
            padding: 16px 24px;
        }
    </style>
    <body>
        <section>
            <div class="content">
                <h1 style="text-align:center">Ask a question</h1>
                <hr />
                <div class="row justify-content-md-center">
                    <div class="col-md-10">
                        <form asp-action="Create" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Text" class="control-label"></label>
                                <textarea asp-for="Text" class="form-control" rows="5" style="resize: none;"></textarea>
                                <span asp-validation-for="Text" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Faculty</label>
                                <select class="form-control faculty-select" name="facultyId">
                                    <option selected value="null">Common</option>
                                    @foreach (var faculty in Model.Faculties)
                                    {
                                        <option value="@faculty.Id">@faculty.Title</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Tags</label>
                                <select class="form-control tags-select" multiple name="tags">
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>
                </div>
                </div>
            </section>
        </body>
                @section Scripts {
                    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
                    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
                    <script src="~/js/question_create.js"></script>
                }

src/askLNU/askLNU/Views/Question/CreatedQuestions.cshtml
@model IEnumerable<askLNU.ViewModels.CreatedQuestionsViewModel>
@using askLNU.BLL.Interfaces
@inject ISignInService SignInService

@{
    ViewData["Title"] = "CreatedQuestions";
}
<style>
    body {
        background-color: lightslategray;
    }

    form {
        margin-bottom: 16px;
    }

    section {
        display: block;
        overflow: auto;
        height: 100%;
        border-radius: 4px;
        background-color: #f8f9fa;
        padding: 16px 24px 40px !important;
    }

    #linksRow {
    width: 344px;
    border: double;
    padding: 6px;
    border-radius: 4px;
    }

    a, h4 {
    color: #cb9d12;
    }

</style>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
    <body>
        <section>
            <div class="content">

                <div class="w3-row-padding" id="linksRow">
                    <a class="link" asp-area="" asp-controller="UserProfile" asp-action="UserProfile">Profile |</a>
                    <a class="link" asp-area="" asp-controller="Question" asp-action="CreatedQuestions">Created questions |</a>
                    <a class="link" asp-area="" asp-controller="Question" asp-action="FavoriteUserQuestions">Favorite questions</a>
                </div>
                <input type="submit" style="float: right" value="Create new" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Question")'" />
                <h1 style="padding: 24px;">Created questions</h1>

                <div class="container-fluid" style="max-width:888px; float:left">
                    @foreach (var item in Model)
                    {
                        @if (!item.IsSolved)
                        {
                            <div class="border border-right-0 border-left-0 border-warning" style="padding: 8px;">
                                <div class="row">
                                    <div class="col-10 text-left">
                                        <h2>
                                            @Html.ActionLink(item.Title, "Details", "Question", new { id = item.Id }, new { style = "text-decoration:none; color: black;" })
                                        </h2>
                                    </div>
                                    @if (User.IsInRole("Moderator"))
                                    {
                                        <div class="col-2 text-right">
                                            <button type="button" class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("DeleteQuestion", "Question", new { questionId = item.Id }) '">
                                                <i class="fa fa-trash-o" style="font-size:15px;color:white"></i>
                                            </button>
                                        </div>
                                    }
                                </div>
                                <div class="row">

                                    <div class="col-7">
                                        @Html.DisplayFor(modelItem => item.Text)

                                    </div>
                                    <div class="col-2 text-center">
                                        <h4>
                                            Rate: @Html.DisplayFor(modelItem => item.Rating)
                                        </h4>
                                        @DateTime.Now.Subtract(item.Date).Days.ToString() days ago
                                    </div>

                                </div>
                            </div>
                        }
                    }

                </div>
                @*<div>
            <input type="submit" style="float:right" value="Create new" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Question")'" />

            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Text)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Rating)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IsSolved)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Date)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Text)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Rating)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsSolved)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>*@
            </div>
        </section>
    </body>


    @section Scripts {
        <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
        <script src="~/js/question_create.js"></script>
        <link href="@Url.Content("~/css/questions.css")" rel="stylesheet" type="text/css" />

    }

src/askLNU/askLNU/Views/Question/Details.cshtml
@model askLNU.ViewModels.QuestionViewModel

@{
    ViewData["Title"] = Model.Title;
    ViewData["Disabled"] = User.IsInRole("User") ? "" : "disabled";
}
<style>
    body {
        background-color: lightslategray;
    }

    form {
        margin-bottom: 16px;
    }

    section {
        display: block;
        overflow: auto;
        height: 100%;
        border-radius: 4px;
        background-color: #f8f9fa;
        padding: 16px 24px;
    }
</style>

<body>
   <section>
      <div class="content">
         <div class="row">

            <div class="col-1 flex-column mt-3 p-0">
                <form id="vote-form">
                    <input type="hidden" value="@Model.Id" id="question-id" />
                    <div class="text-center">
                        <button id="vote-up-button" class="fas fa-chevron-up fa-2x" @ViewData["Disabled"]></button>
                    </div>
                    <div class="text-center" id="question-rating">@Model.Rating</div>
                    <div class="text-center">
                        <button id="vote-down-button" class="fas fa-chevron-down fa-2x" @ViewData["Disabled"]></button>
                    </div>
                </form>
            </div>

            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">
                            @Model.Title
                            <small class="text-muted" id="question-id">#@Model.Id</small>
                        </h2>
                        <p class="card-text">@Model.Text</p>
                    </div>
                </div>

                @if (User.IsInRole("User"))
                {
                    <form class="mt-3">
                        <div class="form-group">
                            <textarea id="answer-text" class="form-control" rows="5" style="resize: none;"></textarea>
                            <input type="hidden" value="@Model.Id" name="question-id" />
                        </div>
                        <div class="form-group">
                            <button id="send-answer-button" class="btn btn-primary">Send answer</button>
                        </div>
                    </form>
                }
                else
                {
                    <div class="alert alert-primary mt-3" role="alert">
                        <a href="@Url.Action("Index", "Login")" class="alert-link">Log In</a> to write answer.
                    </div>
                }

                <div id="answers" style="visibility: hidden;">
                    <div class="row">
                        <div class="col-1 flex-column mt-3 p-0">
                            <form>
                                <input type="hidden" data-bind="id" name="answer-id" />
                                <div class="text-center">
                                    <button type="button" class="fas fa-chevron-up answer-vote-up-button" @ViewData["Disabled"]></button>
                                </div>
                                <div class="text-center answer-rating" data-bind="rating"></div>
                                <div class="text-center">
                                    <button type="button" class="fas fa-chevron-down answer-vote-down-button" @ViewData["Disabled"]></button>
                                </div>
                            </form>
                        </div>
                        <div class="col-11">
                            <div class="card mt-3">
                                <div class="card-body">
                                    <p class="card-text" data-bind="text"></p>
                                </div>
                                <div class="card-footer">
                                    <div class="mb-0">
                                        <strong data-bind="authorName"></strong>
                                        <span> - </span>
                                        <span data-bind="date"></span>
                                        @if (User.IsInRole("Moderator"))
                                        {
                                            <form asp-controller="Answer" asp-action="Delete">
                                                <input type="hidden" name="answerId" data-bind="id"/>
                                                <input type="hidden" name="questionId" value="@Model.Id"/>
                                                <button type="submit" class="btn btn-danger btn-sm">
                                                    <span class="fa fa-trash-o" style="font-size:15px;color:white"></span>
                                                </button>
                                            </form>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-3">
                <div class="media">
                    <img src="@Model.Author.ImageSrc" class="mr-3" width="64">
                    <div class="media-body">
                        <h5 class="mt-0">@Model.Author.UserName</h5>
                        @Model.Date.ToShortDateString()
                    </div>
                </div>

                <div class="mt-3">
                    @foreach (var tag in Model.Tags)
                    {
                        <p class="btn btn-sm btn-dark mb-1">@tag</p>
                        <br />
                    }
                </div>
            </div>

        </div>
      </div>
   </section>
</body>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/transparency/0.9.9/transparency.min.js"></script>
            <script type="text/javascript" src="~/js/question_details.js"></script>
        }